# Generated by Django 3.2.4 on 2022-05-03 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=128)),
                ('clf1', models.BinaryField()),
                ('clf2', models.BinaryField()),
                ('clf3', models.BinaryField()),
                ('clf4', models.BinaryField()),
            ],
        ),
    ]
